"""字幕格式导出：SRT, VTT, ASS, LRC。

所有导出函数接受 SubtitleSegment 列表，返回格式字符串。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


# ── Common types ───────────────────────────────────────────


@dataclass
class SubSegment:
    """通用字幕段，供导出函数消费。"""

    index: int
    start: float
    end: float
    text: str
    speaker: str | None = None


def _fmt_timestamp(seconds: float, fmt: str = "srt") -> str:
    """格式化时间戳。

    SRT/VTT: HH:MM:SS,mmm
    ASS: H:MM:SS.cc
    LRC: [MM:SS.xx]
    """
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    cs = int((seconds - int(seconds)) * 100)

    if fmt == "srt" or fmt == "vtt":
        return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"
    elif fmt == "ass":
        return f"{h:d}:{m:02d}:{s:02d}.{cs:02d}"
    elif fmt == "lrc":
        return f"[{m:02d}:{s:02d}.{cs:02d}]"
    else:
        return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"


# ── SRT ────────────────────────────────────────────────────


def export_srt(segments: list[SubSegment]) -> str:
    """导出 SRT 格式。

    Example:
        1
        00:00:01,000 --> 00:00:05,000
        你好世界
    """
    lines: list[str] = []
    for seg in segments:
        start = _fmt_timestamp(seg.start, "srt")
        end = _fmt_timestamp(seg.end, "srt")
        text = seg.text
        if seg.speaker:
            text = f"[{seg.speaker}] {text}"

        lines.append(str(seg.index))
        lines.append(f"{start} --> {end}")
        lines.append(text)
        lines.append("")  # blank line separator

    return "\n".join(lines).rstrip() + "\n"


# ── VTT ────────────────────────────────────────────────────


def export_vtt(segments: list[SubSegment]) -> str:
    """导出 WebVTT 格式。

    Example:
        WEBVTT

        1
        00:00:01.000 --> 00:00:05.000
        你好世界
    """
    lines = ["WEBVTT", ""]
    for seg in segments:
        # VTT uses . instead of , for milliseconds
        start = _fmt_timestamp(seg.start, "srt").replace(",", ".")
        end = _fmt_timestamp(seg.end, "srt").replace(",", ".")
        text = seg.text
        if seg.speaker:
            text = f"<v {seg.speaker}>{text}</v>"

        lines.append(str(seg.index))
        lines.append(f"{start} --> {end}")
        lines.append(text)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ── ASS ────────────────────────────────────────────────────


def export_ass(
    segments: list[SubSegment],
    *,
    title: str = "Generated by zimu-qwen3",
    font_size: int = 48,
) -> str:
    """导出 ASS (Advanced SubStation Alpha) 格式。

    Example:
        [Script Info]
        Title: ...
        ...
        [Events]
        Dialogue: 0,0:00:01.00,0:00:05.00,Default,,0,0,0,,你好世界
    """
    header = f"""[Script Info]
Title: {title}
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Noto Sans CJK SC,{font_size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"""

    lines = [header]
    for seg in segments:
        start = _fmt_timestamp(seg.start, "ass")
        end = _fmt_timestamp(seg.end, "ass")
        name = seg.speaker or ""
        text = seg.text.replace("\n", "\\N")
        lines.append(
            f"Dialogue: 0,{start},{end},Default,{name},0,0,0,,{text}"
        )

    return "\n".join(lines) + "\n"


# ── LRC ────────────────────────────────────────────────────


def export_lrc(segments: list[SubSegment]) -> str:
    """导出 LRC 歌词格式。

    Example:
        [00:01.00]你好世界
        [00:05.00]第二句
    """
    lines: list[str] = []
    for seg in segments:
        ts = _fmt_timestamp(seg.start, "lrc")
        text = seg.text
        if seg.speaker:
            text = f"[{seg.speaker}] {text}"
        lines.append(f"{ts}{text}")

    return "\n".join(lines) + "\n"


# ── Dispatcher ─────────────────────────────────────────────


def export_subtitles(
    segments: list[SubSegment],
    format: str = "srt",
    **kwargs,
) -> str:
    """按格式导出字幕。

    Args:
        segments: 字幕段列表。
        format: "srt", "vtt", "ass", "lrc"。
        **kwargs: 传递给具体导出函数的额外参数。

    Returns:
        格式字符串。

    Raises:
        ValueError: 不支持的格式。
    """
    exporters = {
        "srt": export_srt,
        "vtt": export_vtt,
        "ass": export_ass,
        "lrc": export_lrc,
    }
    fmt = format.lower()
    if fmt not in exporters:
        raise ValueError(
            f"Unsupported format: {format!r}. Supported: {list(exporters.keys())}"
        )
    return exporters[fmt](segments, **kwargs)
